version: "3.9"
services:
  webswing:
    image: webswing/webswing-eval
    volumes:
      - ./:/opt/app
    ports:
      - "8080:8080"
    env_file:
      - ./env_file.txt
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command: ['start', '--optimized']
    environment:
      JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.upload_scripts=enabled
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_PORT: 5432
      KC_HEALTH_ENABLED: 'true'
      KC_HTTP_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      # KC_HOSTNAME: keycloak.com.au
      # KC_HOSTNAME_PORT: 8180
      KC_HOSTNAME_URL: http://localhost:8180
      KC_PROXY: reencrypt
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KEYCLOAK_LOGLEVEL: DEBUG
    volumes:
      - ./keycloak_data:/opt/keycloak/data/h2
    ports:
      - "8180:8080"
      - "8787:8787" # debug port



